<template>
	<div>
		<svg class="icon"><use xlink:href="#upload"></use></svg>
		<svg class="icon"><use xlink:href="#undo"></use></svg>
		<svg class="icon"><use xlink:href="#sync"></use></svg>
		<svg class="icon"><use xlink:href="#switch-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="#sort-up"></use></svg>
		<svg class="icon"><use xlink:href="#sort-desc"></use></svg>
		<svg class="icon"><use xlink:href="#sort"></use></svg>
		<svg class="icon"><use xlink:href="#redo"></use></svg>
		<svg class="icon"><use xlink:href="#parent"></use></svg>
		<svg class="icon"><use xlink:href="#open"></use></svg>
		<svg class="icon"><use xlink:href="#minimize"></use></svg>
		<svg class="icon"><use xlink:href="#maximize"></use></svg>
		<svg class="icon"><use xlink:href="#logout"></use></svg>
		<svg class="icon"><use xlink:href="#login"></use></svg>
		<svg class="icon"><use xlink:href="#git-pull-request"></use></svg>
		<svg class="icon"><use xlink:href="#git-merge"></use></svg>
		<svg class="icon"><use xlink:href="#git-fork"></use></svg>
		<svg class="icon"><use xlink:href="#git-compare"></use></svg>
		<svg class="icon"><use xlink:href="#git-commit"></use></svg>
		<svg class="icon"><use xlink:href="#git-branch"></use></svg>
		<svg class="icon"><use xlink:href="#forward-up"></use></svg>
		<svg class="icon"><use xlink:href="#forward"></use></svg>
		<svg class="icon"><use xlink:href="#download"></use></svg>
		<svg class="icon"><use xlink:href="#corner-up-right-double"></use></svg>
		<svg class="icon"><use xlink:href="#corner-up-right"></use></svg>
		<svg class="icon"><use xlink:href="#corner-up-left-double"></use></svg>
		<svg class="icon"><use xlink:href="#corner-up-left"></use></svg>
		<svg class="icon"><use xlink:href="#corner-right-up-double"></use></svg>
		<svg class="icon"><use xlink:href="#corner-right-up"></use></svg>
		<svg class="icon"><use xlink:href="#corner-right-down-double"></use></svg>
		<svg class="icon"><use xlink:href="#corner-right-down"></use></svg>
		<svg class="icon"><use xlink:href="#corner-left-up-double"></use></svg>
		<svg class="icon"><use xlink:href="#corner-left-up"></use></svg>
		<svg class="icon"><use xlink:href="#corner-left-down-double"></use></svg>
		<svg class="icon"><use xlink:href="#corner-left-down"></use></svg>
		<svg class="icon"><use xlink:href="#corner-down-right-double"></use></svg>
		<svg class="icon"><use xlink:href="#corner-down-right"></use></svg>
		<svg class="icon"><use xlink:href="#corner-down-left-double"></use></svg>
		<svg class="icon"><use xlink:href="#corner-down-left"></use></svg>
		<svg class="icon"><use xlink:href="#caret-up"></use></svg>
		<svg class="icon"><use xlink:href="#caret-right"></use></svg>
		<svg class="icon"><use xlink:href="#caret-left"></use></svg>
		<svg class="icon"><use xlink:href="#caret-down"></use></svg>
		<svg class="icon"><use xlink:href="#back-up"></use></svg>
		<svg class="icon"><use xlink:href="#back"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-vertical"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-up-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-up-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-up-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-up"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-split"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-right-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-right-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-left-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-left-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-join"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-down-up"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-double-sw-ne"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-double-se-nw"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-double-nw-se"></use></svg>
		<svg class="icon"><use xlink:href="#arrows-double-ne-sw"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-wave-right-up"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-wave-right-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-wave-left-up"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-wave-left-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-vertical"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-up-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-up-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-up"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-top-tail"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-top-square"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-top-circle"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-top-bar"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-right-tail"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-right-square"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-right-circle"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-right-bar"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-ramp-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-ramp-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-loop-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-loop-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-left-tail"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-left-square"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-left-circle"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-left-bar"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-down-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-down-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-diagonal-we"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-diagonal-ew"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bottom-tail"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bottom-square"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bottom-circle"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bottom-bar"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-big-top"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-big-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-big-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-big-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bar-up"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bar-to-up"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bar-to-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bar-to-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bar-to-down"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bar-right"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bar-left"></use></svg>
		<svg class="icon"><use xlink:href="#arrow-bar-down"></use></svg>
		<svg class="icon"><use xlink:href="#angles-up"></use></svg>
		<svg class="icon"><use xlink:href="#angles-right"></use></svg>
		<svg class="icon"><use xlink:href="#angles-left"></use></svg>
		<svg class="icon"><use xlink:href="#angles-down"></use></svg>
		<svg class="icon"><use xlink:href="#angle-up-right"></use></svg>
		<svg class="icon"><use xlink:href="#angle-up-left"></use></svg>
		<svg class="icon"><use xlink:href="#angle-up"></use></svg>
		<svg class="icon"><use xlink:href="#angle-right"></use></svg>
		<svg class="icon"><use xlink:href="#angle-left"></use></svg>
		<svg class="icon"><use xlink:href="#angle-down-right"></use></svg>
		<svg class="icon"><use xlink:href="#angle-down-left"></use></svg>
		<svg class="icon"><use xlink:href="#angle-down"></use></svg>
		<svg class="icon"><use xlink:href="#watch"></use></svg>
		<svg class="icon"><use xlink:href="#television"></use></svg>
		<svg class="icon"><use xlink:href="#tablet"></use></svg>
		<svg class="icon"><use xlink:href="#speaker"></use></svg>
		<svg class="icon"><use xlink:href="#router"></use></svg>
		<svg class="icon"><use xlink:href="#prompt"></use></svg>
		<svg class="icon"><use xlink:href="#printer"></use></svg>
		<svg class="icon"><use xlink:href="#plug"></use></svg>
		<svg class="icon"><use xlink:href="#mouse"></use></svg>
		<svg class="icon"><use xlink:href="#mobile-v"></use></svg>
		<svg class="icon"><use xlink:href="#mobile-h"></use></svg>
		<svg class="icon"><use xlink:href="#laptop"></use></svg>
		<svg class="icon"><use xlink:href="#keyboard"></use></svg>
		<svg class="icon"><use xlink:href="#gamepad"></use></svg>
		<svg class="icon"><use xlink:href="#forms"></use></svg>
		<svg class="icon"><use xlink:href="#folders"></use></svg>
		<svg class="icon"><use xlink:href="#folder-x"></use></svg>
		<svg class="icon"><use xlink:href="#folder-plus"></use></svg>
		<svg class="icon"><use xlink:href="#folder-off"></use></svg>
		<svg class="icon"><use xlink:href="#folder-minus"></use></svg>
		<svg class="icon"><use xlink:href="#folder"></use></svg>
		<svg class="icon"><use xlink:href="#floppy"></use></svg>
		<svg class="icon"><use xlink:href="#files-off"></use></svg>
		<svg class="icon"><use xlink:href="#files"></use></svg>
		<svg class="icon"><use xlink:href="#file-zip"></use></svg>
		<svg class="icon"><use xlink:href="#file-x"></use></svg>
		<svg class="icon"><use xlink:href="#file-upload"></use></svg>
		<svg class="icon"><use xlink:href="#file-text"></use></svg>
		<svg class="icon"><use xlink:href="#file-symlink"></use></svg>
		<svg class="icon"><use xlink:href="#file-shredder"></use></svg>
		<svg class="icon"><use xlink:href="#file-search"></use></svg>
		<svg class="icon"><use xlink:href="#file-report"></use></svg>
		<svg class="icon"><use xlink:href="#file-plus"></use></svg>
		<svg class="icon"><use xlink:href="#file-phone"></use></svg>
		<svg class="icon"><use xlink:href="#file-off"></use></svg>
		<svg class="icon"><use xlink:href="#file-music"></use></svg>
		<svg class="icon"><use xlink:href="#file-minus"></use></svg>
		<svg class="icon"><use xlink:href="#file-like"></use></svg>
		<svg class="icon"><use xlink:href="#file-invoice"></use></svg>
		<svg class="icon"><use xlink:href="#file-info"></use></svg>
		<svg class="icon"><use xlink:href="#file-import"></use></svg>
		<svg class="icon"><use xlink:href="#file-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="#file-export"></use></svg>
		<svg class="icon"><use xlink:href="#file-download"></use></svg>
		<svg class="icon"><use xlink:href="#file-dislike"></use></svg>
		<svg class="icon"><use xlink:href="#file-diff"></use></svg>
		<svg class="icon"><use xlink:href="#file-code-2"></use></svg>
		<svg class="icon"><use xlink:href="#file-code"></use></svg>
		<svg class="icon"><use xlink:href="#file-check"></use></svg>
		<svg class="icon"><use xlink:href="#file-certificate"></use></svg>
		<svg class="icon"><use xlink:href="#file-analytics"></use></svg>
		<svg class="icon"><use xlink:href="#file-alert"></use></svg>
		<svg class="icon"><use xlink:href="#file"></use></svg>
		<svg class="icon"><use xlink:href="#desktop"></use></svg>
		<svg class="icon"><use xlink:href="#database"></use></svg>
		<svg class="icon"><use xlink:href="#dashboard"></use></svg>
		<svg class="icon"><use xlink:href="#command"></use></svg>
		<svg class="icon"><use xlink:href="#code"></use></svg>
		<svg class="icon"><use xlink:href="#bucket"></use></svg>
		<svg class="icon"><use xlink:href="#browser"></use></svg>
		<svg class="icon"><use xlink:href="#brackets"></use></svg>
		<svg class="icon"><use xlink:href="#braces"></use></svg>
		<svg class="icon"><use xlink:href="#backspace"></use></svg>
		<svg class="icon"><use xlink:href="#at"></use></svg>
		<svg class="icon"><use xlink:href="#archive"></use></svg>
		<svg class="icon"><use xlink:href="#analytics"></use></svg>
		<svg class="icon"><use xlink:href="#zloty"></use></svg>
		<svg class="icon"><use xlink:href="#yen"></use></svg>
		<svg class="icon"><use xlink:href="#won"></use></svg>
		<svg class="icon"><use xlink:href="#tugrik"></use></svg>
		<svg class="icon"><use xlink:href="#taka"></use></svg>
		<svg class="icon"><use xlink:href="#shekel"></use></svg>
		<svg class="icon"><use xlink:href="#rupee"></use></svg>
		<svg class="icon"><use xlink:href="#rubel"></use></svg>
		<svg class="icon"><use xlink:href="#riyal"></use></svg>
		<svg class="icon"><use xlink:href="#ripple"></use></svg>
		<svg class="icon"><use xlink:href="#renminbi"></use></svg>
		<svg class="icon"><use xlink:href="#real"></use></svg>
		<svg class="icon"><use xlink:href="#pound"></use></svg>
		<svg class="icon"><use xlink:href="#naira"></use></svg>
		<svg class="icon"><use xlink:href="#litecoin"></use></svg>
		<svg class="icon"><use xlink:href="#lira"></use></svg>
		<svg class="icon"><use xlink:href="#leu"></use></svg>
		<svg class="icon"><use xlink:href="#krone-swedish"></use></svg>
		<svg class="icon"><use xlink:href="#krone-danish"></use></svg>
		<svg class="icon"><use xlink:href="#krone-czech"></use></svg>
		<svg class="icon"><use xlink:href="#frank"></use></svg>
		<svg class="icon"><use xlink:href="#forint"></use></svg>
		<svg class="icon"><use xlink:href="#euro"></use></svg>
		<svg class="icon"><use xlink:href="#ethereum"></use></svg>
		<svg class="icon"><use xlink:href="#dollar-singapore"></use></svg>
		<svg class="icon"><use xlink:href="#dollar-canadian"></use></svg>
		<svg class="icon"><use xlink:href="#dollar-australian"></use></svg>
		<svg class="icon"><use xlink:href="#dollar"></use></svg>
		<svg class="icon"><use xlink:href="#dirham"></use></svg>
		<svg class="icon"><use xlink:href="#dinar"></use></svg>
		<svg class="icon"><use xlink:href="#cent"></use></svg>
		<svg class="icon"><use xlink:href="#bitcoin"></use></svg>
		<svg class="icon"><use xlink:href="#bath"></use></svg>
		<svg class="icon"><use xlink:href="#bahraini"></use></svg>
		<svg class="icon"><use xlink:href="#playlist"></use></svg>
		<svg class="icon"><use xlink:href="#player-track-prev"></use></svg>
		<svg class="icon"><use xlink:href="#player-track-next"></use></svg>
		<svg class="icon"><use xlink:href="#player-stop"></use></svg>
		<svg class="icon"><use xlink:href="#player-skip-forward"></use></svg>
		<svg class="icon"><use xlink:href="#player-skip-back"></use></svg>
		<svg class="icon"><use xlink:href="#player-record"></use></svg>
		<svg class="icon"><use xlink:href="#player-play"></use></svg>
		<svg class="icon"><use xlink:href="#player-pause"></use></svg>
		<svg class="icon"><use xlink:href="#page-break"></use></svg>
		<svg class="icon"><use xlink:href="#line-height"></use></svg>
		<svg class="icon"><use xlink:href="#hash"></use></svg>
		<svg class="icon"><use xlink:href="#flip-vertical"></use></svg>
		<svg class="icon"><use xlink:href="#flip-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="#eraser"></use></svg>
		<svg class="icon"><use xlink:href="#edit"></use></svg>
		<svg class="icon"><use xlink:href="#cut"></use></svg>
		<svg class="icon"><use xlink:href="#cursor-text"></use></svg>
		<svg class="icon"><use xlink:href="#crop"></use></svg>
		<svg class="icon"><use xlink:href="#copy"></use></svg>
		<svg class="icon"><use xlink:href="#column-insert-right"></use></svg>
		<svg class="icon"><use xlink:href="#column-insert-left"></use></svg>
		<svg class="icon"><use xlink:href="#color-picker"></use></svg>
		<svg class="icon"><use xlink:href="#clipboard"></use></svg>
		<svg class="icon"><use xlink:href="#chart-pie"></use></svg>
		<svg class="icon"><use xlink:href="#chart-line"></use></svg>
		<svg class="icon"><use xlink:href="#chart-infographic"></use></svg>
		<svg class="icon"><use xlink:href="#chart-dots"></use></svg>
		<svg class="icon"><use xlink:href="#chart-donut"></use></svg>
		<svg class="icon"><use xlink:href="#chart-circles"></use></svg>
		<svg class="icon"><use xlink:href="#chart-candle"></use></svg>
		<svg class="icon"><use xlink:href="#chart-bubble"></use></svg>
		<svg class="icon"><use xlink:href="#chart-bar"></use></svg>
		<svg class="icon"><use xlink:href="#chart-arrows-vertical"></use></svg>
		<svg class="icon"><use xlink:href="#chart-arrows"></use></svg>
		<svg class="icon"><use xlink:href="#chart-area-line"></use></svg>
		<svg class="icon"><use xlink:href="#chart-area"></use></svg>
		<svg class="icon"><use xlink:href="#chart-arcs"></use></svg>
		<svg class="icon"><use xlink:href="#brush"></use></svg>
		<svg class="icon"><use xlink:href="#aspect-ratio"></use></svg>
		<svg class="icon"><use xlink:href="#artboard"></use></svg>
		<svg class="icon"><use xlink:href="#align-right"></use></svg>
		<svg class="icon"><use xlink:href="#align-left"></use></svg>
		<svg class="icon"><use xlink:href="#align-justified"></use></svg>
		<svg class="icon"><use xlink:href="#align-center"></use></svg>
		<svg class="icon"><use xlink:href="#circle-square"></use></svg>
		<svg class="icon"><use xlink:href="#visible"></use></svg>
		<svg class="icon"><use xlink:href="#users"></use></svg>
		<svg class="icon"><use xlink:href="#user"></use></svg>
		<svg class="icon"><use xlink:href="#unlink"></use></svg>
		<svg class="icon"><use xlink:href="#trash"></use></svg>
		<svg class="icon"><use xlink:href="#time"></use></svg>
		<svg class="icon"><use xlink:href="#target"></use></svg>
		<svg class="icon"><use xlink:href="#search"></use></svg>
		<svg class="icon"><use xlink:href="#record-mail"></use></svg>
		<svg class="icon"><use xlink:href="#power"></use></svg>
		<svg class="icon"><use xlink:href="#pinned"></use></svg>
		<svg class="icon"><use xlink:href="#pin"></use></svg>
		<svg class="icon"><use xlink:href="#photo"></use></svg>
		<svg class="icon"><use xlink:href="#phone"></use></svg>
		<svg class="icon"><use xlink:href="#perspective"></use></svg>
		<svg class="icon"><use xlink:href="#panorama-vertical"></use></svg>
		<svg class="icon"><use xlink:href="#panorama-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="#octagon"></use></svg>
		<svg class="icon"><use xlink:href="#note"></use></svg>
		<svg class="icon"><use xlink:href="#mood-suprised"></use></svg>
		<svg class="icon"><use xlink:href="#mood-smile"></use></svg>
		<svg class="icon"><use xlink:href="#mood-sad"></use></svg>
		<svg class="icon"><use xlink:href="#mood-neutral"></use></svg>
		<svg class="icon"><use xlink:href="#mood-empty"></use></svg>
		<svg class="icon"><use xlink:href="#mood-confuzed"></use></svg>
		<svg class="icon"><use xlink:href="#mist"></use></svg>
		<svg class="icon"><use xlink:href="#minimize"></use></svg>
		<svg class="icon"><use xlink:href="#microphone-off"></use></svg>
		<svg class="icon"><use xlink:href="#microphone"></use></svg>
		<svg class="icon"><use xlink:href="#message-dots"></use></svg>
		<svg class="icon"><use xlink:href="#message-circle"></use></svg>
		<svg class="icon"><use xlink:href="#message"></use></svg>
		<svg class="icon"><use xlink:href="#menu"></use></svg>
		<svg class="icon"><use xlink:href="#maximize"></use></svg>
		<svg class="icon"><use xlink:href="#map-pin"></use></svg>
		<svg class="icon"><use xlink:href="#map"></use></svg>
		<svg class="icon"><use xlink:href="#lozange"></use></svg>
		<svg class="icon"><use xlink:href="#lock-open"></use></svg>
		<svg class="icon"><use xlink:href="#lock"></use></svg>
		<svg class="icon"><use xlink:href="#location"></use></svg>
		<svg class="icon"><use xlink:href="#live-view"></use></svg>
		<svg class="icon"><use xlink:href="#list-search"></use></svg>
		<svg class="icon"><use xlink:href="#list-check"></use></svg>
		<svg class="icon"><use xlink:href="#list"></use></svg>
		<svg class="icon"><use xlink:href="#link"></use></svg>
		<svg class="icon"><use xlink:href="#line-dotted"></use></svg>
		<svg class="icon"><use xlink:href="#line-dashed"></use></svg>
		<svg class="icon"><use xlink:href="#line"></use></svg>
		<svg class="icon"><use xlink:href="#layout-list"></use></svg>
		<svg class="icon"><use xlink:href="#layout-grid"></use></svg>
		<svg class="icon"><use xlink:href="#layout-columns"></use></svg>
		<svg class="icon"><use xlink:href="#layout-cards"></use></svg>
		<svg class="icon"><use xlink:href="#layout"></use></svg>
		<svg class="icon"><use xlink:href="#l8n"></use></svg>
		<svg class="icon"><use xlink:href="#history"></use></svg>
		<svg class="icon"><use xlink:href="#hierarchy"></use></svg>
		<svg class="icon"><use xlink:href="#hidden"></use></svg>
		<svg class="icon"><use xlink:href="#hexagon"></use></svg>
		<svg class="icon"><use xlink:href="#hand-rock"></use></svg>
		<svg class="icon"><use xlink:href="#grip-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="#grid-dots"></use></svg>
		<svg class="icon"><use xlink:href="#grain"></use></svg>
		<svg class="icon"><use xlink:href="#globe"></use></svg>
		<svg class="icon"><use xlink:href="#focus"></use></svg>
		<svg class="icon"><use xlink:href="#filter"></use></svg>
		<svg class="icon"><use xlink:href="#face-id"></use></svg>
		<svg class="icon"><use xlink:href="#envelope-opened"></use></svg>
		<svg class="icon"><use xlink:href="#envelope"></use></svg>
		<svg class="icon"><use xlink:href="#drag-drop"></use></svg>
		<svg class="icon"><use xlink:href="#drag"></use></svg>
		<svg class="icon"><use xlink:href="#dots-diagonal-2"></use></svg>
		<svg class="icon"><use xlink:href="#dots-diagonal"></use></svg>
		<svg class="icon"><use xlink:href="#dots"></use></svg>
		<svg class="icon"><use xlink:href="#dot-dot-dot"></use></svg>
		<svg class="icon"><use xlink:href="#disabled"></use></svg>
		<svg class="icon"><use xlink:href="#crosshair"></use></svg>
		<svg class="icon"><use xlink:href="#credit-card"></use></svg>
		<svg class="icon"><use xlink:href="#cog"></use></svg>
		<svg class="icon"><use xlink:href="#click"></use></svg>
		<svg class="icon"><use xlink:href="#circles"></use></svg>
		<svg class="icon"><use xlink:href="#circle-half-vertical"></use></svg>
		<svg class="icon"><use xlink:href="#circle-half"></use></svg>
		<svg class="icon"><use xlink:href="#circle"></use></svg>
		<svg class="icon"><use xlink:href="#cast"></use></svg>
		<svg class="icon"><use xlink:href="#capture"></use></svg>
		<svg class="icon"><use xlink:href="#calendar"></use></svg>
		<svg class="icon"><use xlink:href="#bulb-off"></use></svg>
		<svg class="icon"><use xlink:href="#bulb"></use></svg>
		<svg class="icon"><use xlink:href="#bug"></use></svg>
		<svg class="icon"><use xlink:href="#bookmarks"></use></svg>
		<svg class="icon"><use xlink:href="#bookmark-off"></use></svg>
		<svg class="icon"><use xlink:href="#bookmark"></use></svg>
		<svg class="icon"><use xlink:href="#bag"></use></svg>
		<svg class="icon"><use xlink:href="#apps"></use></svg>
		<svg class="icon"><use xlink:href="#alarm"></use></svg>
		<svg class="icon"><use xlink:href="#adjustments-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="#adjustments"></use></svg>
		<svg class="icon"><use xlink:href="#a-b"></use></svg>
		<svg class="icon"><use xlink:href="#2fa"></use></svg>
		<svg class="icon"><use xlink:href="#star-full"></use></svg>
		<svg class="icon"><use xlink:href="#star"></use></svg>
		<svg class="icon"><use xlink:href="#speedboat"></use></svg>
		<svg class="icon"><use xlink:href="#scooter"></use></svg>
		<svg class="icon"><use xlink:href="#sailboat"></use></svg>
		<svg class="icon"><use xlink:href="#ruler"></use></svg>
		<svg class="icon"><use xlink:href="#rocket"></use></svg>
		<svg class="icon"><use xlink:href="#recycle"></use></svg>
		<svg class="icon"><use xlink:href="#propeller"></use></svg>
		<svg class="icon"><use xlink:href="#play-card"></use></svg>
		<svg class="icon"><use xlink:href="#plant"></use></svg>
		<svg class="icon"><use xlink:href="#planet"></use></svg>
		<svg class="icon"><use xlink:href="#plane-departure"></use></svg>
		<svg class="icon"><use xlink:href="#plane-arrival"></use></svg>
		<svg class="icon"><use xlink:href="#plane"></use></svg>
		<svg class="icon"><use xlink:href="#pizza"></use></svg>
		<svg class="icon"><use xlink:href="#pill"></use></svg>
		<svg class="icon"><use xlink:href="#pennant"></use></svg>
		<svg class="icon"><use xlink:href="#pencil"></use></svg>
		<svg class="icon"><use xlink:href="#peace"></use></svg>
		<svg class="icon"><use xlink:href="#paperclip"></use></svg>
		<svg class="icon"><use xlink:href="#paint"></use></svg>
		<svg class="icon"><use xlink:href="#music"></use></svg>
		<svg class="icon"><use xlink:href="#mug"></use></svg>
		<svg class="icon"><use xlink:href="#motorbike"></use></svg>
		<svg class="icon"><use xlink:href="#moped"></use></svg>
		<svg class="icon"><use xlink:href="#moon"></use></svg>
		<svg class="icon"><use xlink:href="#mars"></use></svg>
		<svg class="icon"><use xlink:href="#magnet"></use></svg>
		<svg class="icon"><use xlink:href="#lotus"></use></svg>
		<svg class="icon"><use xlink:href="#lifeboy"></use></svg>
		<svg class="icon"><use xlink:href="#license"></use></svg>
		<svg class="icon"><use xlink:href="#leaf"></use></svg>
		<svg class="icon"><use xlink:href="#key"></use></svg>
		<svg class="icon"><use xlink:href="#inbox"></use></svg>
		<svg class="icon"><use xlink:href="#ice-cream"></use></svg>
		<svg class="icon"><use xlink:href="#home"></use></svg>
		<svg class="icon"><use xlink:href="#helicopter"></use></svg>
		<svg class="icon"><use xlink:href="#heart"></use></svg>
		<svg class="icon"><use xlink:href="#headphones"></use></svg>
		<svg class="icon"><use xlink:href="#globe"></use></svg>
		<svg class="icon"><use xlink:href="#glass"></use></svg>
		<svg class="icon"><use xlink:href="#gift"></use></svg>
		<svg class="icon"><use xlink:href="#ghost"></use></svg>
		<svg class="icon"><use xlink:href="#geometry"></use></svg>
		<svg class="icon"><use xlink:href="#forklift"></use></svg>
		<svg class="icon"><use xlink:href="#flower"></use></svg>
		<svg class="icon"><use xlink:href="#flask"></use></svg>
		<svg class="icon"><use xlink:href="#flame"></use></svg>
		<svg class="icon"><use xlink:href="#firetruck"></use></svg>
		<svg class="icon"><use xlink:href="#eyeglass"></use></svg>
		<svg class="icon"><use xlink:href="#egg"></use></svg>
		<svg class="icon"><use xlink:href="#ear"></use></svg>
		<svg class="icon"><use xlink:href="#droplet"></use></svg>
		<svg class="icon"><use xlink:href="#dna"></use></svg>
		<svg class="icon"><use xlink:href="#directions"></use></svg>
		<svg class="icon"><use xlink:href="#diamond"></use></svg>
		<svg class="icon"><use xlink:href="#curly-loop"></use></svg>
		<svg class="icon"><use xlink:href="#crown"></use></svg>
		<svg class="icon"><use xlink:href="#comet"></use></svg>
		<svg class="icon"><use xlink:href="#color-swatch"></use></svg>
		<svg class="icon"><use xlink:href="#cloud"></use></svg>
		<svg class="icon"><use xlink:href="#christmas-tree"></use></svg>
		<svg class="icon"><use xlink:href="#cash"></use></svg>
		<svg class="icon"><use xlink:href="#caravan"></use></svg>
		<svg class="icon"><use xlink:href="#car"></use></svg>
		<svg class="icon"><use xlink:href="#camera"></use></svg>
		<svg class="icon"><use xlink:href="#bus"></use></svg>
		<svg class="icon"><use xlink:href="#bullhorn"></use></svg>
		<svg class="icon"><use xlink:href="#bulldozer"></use></svg>
		<svg class="icon"><use xlink:href="#building-warehouse"></use></svg>
		<svg class="icon"><use xlink:href="#building-store"></use></svg>
		<svg class="icon"><use xlink:href="#building-skyscraper"></use></svg>
		<svg class="icon"><use xlink:href="#building-pavilon"></use></svg>
		<svg class="icon"><use xlink:href="#building-monument"></use></svg>
		<svg class="icon"><use xlink:href="#building-lighthouse"></use></svg>
		<svg class="icon"><use xlink:href="#building-hospital"></use></svg>
		<svg class="icon"><use xlink:href="#building-fortress"></use></svg>
		<svg class="icon"><use xlink:href="#building-factory"></use></svg>
		<svg class="icon"><use xlink:href="#building-cottage"></use></svg>
		<svg class="icon"><use xlink:href="#building-community"></use></svg>
		<svg class="icon"><use xlink:href="#building-church"></use></svg>
		<svg class="icon"><use xlink:href="#building-castle"></use></svg>
		<svg class="icon"><use xlink:href="#building-carousel"></use></svg>
		<svg class="icon"><use xlink:href="#building-bridge-2"></use></svg>
		<svg class="icon"><use xlink:href="#building-bridge"></use></svg>
		<svg class="icon"><use xlink:href="#building-bank"></use></svg>
		<svg class="icon"><use xlink:href="#building-arch"></use></svg>
		<svg class="icon"><use xlink:href="#building"></use></svg>
		<svg class="icon"><use xlink:href="#briefcase"></use></svg>
		<svg class="icon"><use xlink:href="#book"></use></svg>
		<svg class="icon"><use xlink:href="#bone"></use></svg>
		<svg class="icon"><use xlink:href="#bolt-off"></use></svg>
		<svg class="icon"><use xlink:href="#bolt"></use></svg>
		<svg class="icon"><use xlink:href="#bike"></use></svg>
		<svg class="icon"><use xlink:href="#bed"></use></svg>
		<svg class="icon"><use xlink:href="#battery-automotive"></use></svg>
		<svg class="icon"><use xlink:href="#bandage"></use></svg>
		<svg class="icon"><use xlink:href="#ball-tennis"></use></svg>
		<svg class="icon"><use xlink:href="#ball-football"></use></svg>
		<svg class="icon"><use xlink:href="#ball-bowling"></use></svg>
		<svg class="icon"><use xlink:href="#ball-american-football"></use></svg>
		<svg class="icon"><use xlink:href="#award"></use></svg>
		<svg class="icon"><use xlink:href="#atom"></use></svg>
		<svg class="icon"><use xlink:href="#alien"></use></svg>
		<svg class="icon"><use xlink:href="#aerial-lift"></use></svg>
		<svg class="icon"><use xlink:href="#activity"></use></svg>
		<svg class="icon"><use xlink:href="#divide"></use></svg>
		<svg class="icon"><use xlink:href="#equals"></use></svg>
		<svg class="icon"><use xlink:href="#calculator"></use></svg>
		<svg class="icon"><use xlink:href="#infinity"></use></svg>
		<svg class="icon"><use xlink:href="#math-function"></use></svg>
		<svg class="icon"><use xlink:href="#math-symbols"></use></svg>
		<svg class="icon"><use xlink:href="#math"></use></svg>
		<svg class="icon"><use xlink:href="#minus"></use></svg>
		<svg class="icon"><use xlink:href="#parentheses"></use></svg>
		<svg class="icon"><use xlink:href="#omega"></use></svg>
		<svg class="icon"><use xlink:href="#percent"></use></svg>
		<svg class="icon"><use xlink:href="#plus"></use></svg>
		<svg class="icon"><use xlink:href="#not-equal"></use></svg>
		<svg class="icon"><use xlink:href="#greater-than"></use></svg>
		<svg class="icon"><use xlink:href="#less-than"></use></svg>
		<svg class="icon"><use xlink:href="#greater-than-equal"></use></svg>
		<svg class="icon"><use xlink:href="#less-than-equal"></use></svg>
		<svg class="icon"><use xlink:href="#workflow"></use></svg>
		<svg class="icon"><use xlink:href="#eatin"></use></svg>
		<svg class="icon"><use xlink:href="#cms"></use></svg>
		<svg class="icon"><use xlink:href="#embed"></use></svg>
		<svg class="icon"><use xlink:href="#lightspeed"></use></svg>
		<svg class="icon"><use xlink:href="#shop"></use></svg>
		<svg class="icon"><use xlink:href="#pickup"></use></svg>
		<svg class="icon"><use xlink:href="#reporting"></use></svg>
		<svg class="icon"><use xlink:href="#delivery"></use></svg>
		<svg class="icon"><use xlink:href="#virtual"></use></svg>
		<svg class="icon"><use xlink:href="#access-point-off"></use></svg>
		<svg class="icon"><use xlink:href="#access-point"></use></svg>
		<svg class="icon"><use xlink:href="#antenna-bars-1"></use></svg>
		<svg class="icon"><use xlink:href="#antenna-bars-2"></use></svg>
		<svg class="icon"><use xlink:href="#antenna-bars-3"></use></svg>
		<svg class="icon"><use xlink:href="#antenna-bars-4"></use></svg>
		<svg class="icon"><use xlink:href="#antenna-bars-5"></use></svg>
		<svg class="icon"><use xlink:href="#alert-circle"></use></svg>
		<svg class="icon"><use xlink:href="#exclamation"></use></svg>
		<svg class="icon"><use xlink:href="#alert-octagon"></use></svg>
		<svg class="icon"><use xlink:href="#alert-triangle"></use></svg>
		<svg class="icon"><use xlink:href="#ban"></use></svg>
		<svg class="icon"><use xlink:href="#battery-1"></use></svg>
		<svg class="icon"><use xlink:href="#battery-2"></use></svg>
		<svg class="icon"><use xlink:href="#battery-3"></use></svg>
		<svg class="icon"><use xlink:href="#battery-charging"></use></svg>
		<svg class="icon"><use xlink:href="#battery"></use></svg>
		<svg class="icon"><use xlink:href="#bell-minus"></use></svg>
		<svg class="icon"><use xlink:href="#bell-off"></use></svg>
		<svg class="icon"><use xlink:href="#bell-plus"></use></svg>
		<svg class="icon"><use xlink:href="#bell"></use></svg>
		<svg class="icon"><use xlink:href="#bluetooth-connected"></use></svg>
		<svg class="icon"><use xlink:href="#bluetooth-off"></use></svg>
		<svg class="icon"><use xlink:href="#bluetooth"></use></svg>
		<svg class="icon"><use xlink:href="#bell-x"></use></svg>
		<svg class="icon"><use xlink:href="#brightness-down"></use></svg>
		<svg class="icon"><use xlink:href="#brightness-up"></use></svg>
		<svg class="icon"><use xlink:href="#check"></use></svg>
		<svg class="icon"><use xlink:href="#checkbox"></use></svg>
		<svg class="icon"><use xlink:href="#checks"></use></svg>
		<svg class="icon"><use xlink:href="#contrast"></use></svg>
		<svg class="icon"><use xlink:href="#compass"></use></svg>
		<svg class="icon"><use xlink:href="#flag-2"></use></svg>
		<svg class="icon"><use xlink:href="#flag-3"></use></svg>
		<svg class="icon"><use xlink:href="#flag"></use></svg>
		<svg class="icon"><use xlink:href="#forbid"></use></svg>
		<svg class="icon"><use xlink:href="#help"></use></svg>
		<svg class="icon"><use xlink:href="#info-circle"></use></svg>
		<svg class="icon"><use xlink:href="#info"></use></svg>
		<svg class="icon"><use xlink:href="#info-square"></use></svg>
		<svg class="icon"><use xlink:href="#notification"></use></svg>
		<svg class="icon"><use xlink:href="#question-mark"></use></svg>
		<svg class="icon"><use xlink:href="#asterisk"></use></svg>
		<svg class="icon"><use xlink:href="#cross"></use></svg>
		<svg class="icon"><use xlink:href="#wifi-3"></use></svg>
		<svg class="icon"><use xlink:href="#wifi-2"></use></svg>
		<svg class="icon"><use xlink:href="#wifi-1"></use></svg>
		<svg class="icon"><use xlink:href="#wifi"></use></svg>
		<svg class="icon"><use xlink:href="#wifi"></use></svg></div>