<template>
	<div>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#upload"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#undo"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#sync"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#switch-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#sort-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#sort-desc"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#sort"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#redo"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#parent"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#open"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#minimize"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#maximize"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#logout"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#login"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#git-pull-request"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#git-merge"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#git-fork"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#git-compare"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#git-commit"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#git-branch"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#forward-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#forward"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#download"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-up-right-double"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-up-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-up-left-double"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-up-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-right-up-double"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-right-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-right-down-double"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-right-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-left-up-double"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-left-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-left-down-double"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-left-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-down-right-double"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-down-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-down-left-double"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#corner-down-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#caret-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#caret-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#caret-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#caret-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#back-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#back"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-vertical"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-up-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-up-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-up-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-split"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-right-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-right-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-left-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-left-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-join"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-down-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-double-sw-ne"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-double-se-nw"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-double-nw-se"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrows-double-ne-sw"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-wave-right-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-wave-right-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-wave-left-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-wave-left-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-vertical"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-up-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-up-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-top-tail"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-top-square"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-top-circle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-top-bar"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-right-tail"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-right-square"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-right-circle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-right-bar"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-ramp-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-ramp-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-loop-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-loop-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-left-tail"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-left-square"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-left-circle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-left-bar"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-down-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-down-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-diagonal-we"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-diagonal-ew"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bottom-tail"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bottom-square"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bottom-circle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bottom-bar"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-big-top"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-big-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-big-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-big-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bar-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bar-to-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bar-to-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bar-to-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bar-to-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bar-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bar-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#arrow-bar-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angles-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angles-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angles-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angles-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angle-up-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angle-up-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angle-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angle-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angle-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angle-down-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angle-down-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#angle-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#watch"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#television"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#tablet"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#speaker"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#router"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#prompt"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#printer"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#plug"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mouse"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mobile-v"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mobile-h"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#laptop"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#keyboard"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#gamepad"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#forms"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#folders"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#folder-x"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#folder-plus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#folder-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#folder-minus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#folder"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#floppy"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#files-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#files"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-zip"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-x"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-upload"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-text"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-symlink"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-shredder"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-search"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-report"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-plus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-phone"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-music"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-minus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-like"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-invoice"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-info"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-import"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-export"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-download"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-dislike"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-diff"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-code-2"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-code"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-check"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-certificate"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-analytics"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file-alert"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#file"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#desktop"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#database"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dashboard"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#command"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#code"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bucket"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#browser"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#brackets"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#braces"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#backspace"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#at"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#archive"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#analytics"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#zloty"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#yen"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#won"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#tugrik"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#taka"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#shekel"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#rupee"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#rubel"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#riyal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ripple"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#renminbi"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#real"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#pound"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#naira"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#litecoin"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#lira"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#leu"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#krone-swedish"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#krone-danish"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#krone-czech"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#frank"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#forint"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#euro"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ethereum"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dollar-singapore"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dollar-canadian"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dollar-australian"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dollar"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dirham"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dinar"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cent"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bitcoin"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bath"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bahraini"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#playlist"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#player-track-prev"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#player-track-next"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#player-stop"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#player-skip-forward"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#player-skip-back"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#player-record"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#player-play"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#player-pause"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#page-break"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#line-height"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#hash"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#flip-vertical"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#flip-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#eraser"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#edit"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cut"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cursor-text"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#crop"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#copy"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#column-insert-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#column-insert-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#color-picker"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#clipboard"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-pie"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-line"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-infographic"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-dots"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-donut"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-circles"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-candle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-bubble"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-bar"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-arrows-vertical"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-arrows"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-area-line"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-area"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#chart-arcs"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#brush"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#aspect-ratio"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#artboard"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#align-right"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#align-left"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#align-justified"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#align-center"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#circle-square"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#visible"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#users"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#user"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#unlink"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#trash"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#time"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#target"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#search"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#record-mail"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#power"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#pinned"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#pin"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#photo"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#phone"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#perspective"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#panorama-vertical"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#panorama-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#octagon"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#note"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mood-suprised"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mood-smile"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mood-sad"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mood-neutral"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mood-empty"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mood-confuzed"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mist"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#minimize"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#microphone-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#microphone"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#message-dots"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#message-circle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#message"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#menu"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#maximize"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#map-pin"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#map"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#lozange"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#lock-open"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#lock"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#location"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#live-view"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#list-search"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#list-check"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#list"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#link"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#line-dotted"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#line-dashed"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#line"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#layout-list"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#layout-grid"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#layout-columns"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#layout-cards"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#layout"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#l8n"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#history"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#hierarchy"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#hidden"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#hexagon"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#hand-rock"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#grip-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#grid-dots"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#grain"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#globe"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#focus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#filter"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#face-id"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#envelope-opened"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#envelope"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#drag-drop"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#drag"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dots-diagonal-2"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dots-diagonal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dots"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dot-dot-dot"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#disabled"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#crosshair"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#credit-card"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cog"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#click"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#circles"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#circle-half-vertical"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#circle-half"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#circle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cast"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#capture"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#calendar"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bulb-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bulb"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bug"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bookmarks"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bookmark-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bookmark"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bag"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#apps"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#alarm"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#adjustments-horizontal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#adjustments"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#a-b"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#2fa"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#star-full"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#star"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#speedboat"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#scooter"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#sailboat"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ruler"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#rocket"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#recycle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#propeller"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#play-card"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#plant"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#planet"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#plane-departure"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#plane-arrival"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#plane"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#pizza"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#pill"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#pennant"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#pencil"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#peace"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#paperclip"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#paint"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#music"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mug"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#motorbike"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#moped"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#moon"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#mars"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#magnet"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#lotus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#lifeboy"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#license"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#leaf"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#key"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#inbox"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ice-cream"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#home"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#helicopter"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#heart"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#headphones"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#globe"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#glass"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#gift"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ghost"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#geometry"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#forklift"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#flower"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#flask"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#flame"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#firetruck"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#eyeglass"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#egg"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ear"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#droplet"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#dna"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#directions"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#diamond"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#curly-loop"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#crown"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#comet"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#color-swatch"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cloud"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#christmas-tree"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cash"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#caravan"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#car"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#camera"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bullhorn"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bulldozer"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-warehouse"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-store"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-skyscraper"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-pavilon"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-monument"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-lighthouse"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-hospital"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-fortress"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-factory"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-cottage"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-community"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-church"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-castle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-carousel"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-bridge-2"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-bridge"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-bank"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building-arch"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#building"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#briefcase"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#book"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bone"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bolt-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bolt"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bike"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bed"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#battery-automotive"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bandage"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ball-tennis"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ball-football"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ball-bowling"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ball-american-football"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#award"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#atom"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#alien"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#aerial-lift"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#activity"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#divide"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#equals"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#calculator"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#infinity"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#math-function"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#math-symbols"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#math"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#minus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#parentheses"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#omega"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#percent"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#plus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#not-equal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#greater-than"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#less-than"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#greater-than-equal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#less-than-equal"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#workflow"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#eatin"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cms"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#embed"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#lightspeed"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#shop"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#pickup"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#reporting"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#delivery"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#virtual"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#access-point-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#access-point"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#antenna-bars-1"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#antenna-bars-2"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#antenna-bars-3"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#antenna-bars-4"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#antenna-bars-5"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#alert-circle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#exclamation"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#alert-octagon"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#alert-triangle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#ban"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#battery-1"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#battery-2"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#battery-3"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#battery-charging"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#battery"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bell-minus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bell-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bell-plus"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bell"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bluetooth-connected"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bluetooth-off"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bluetooth"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#bell-x"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#brightness-down"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#brightness-up"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#check"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#checkbox"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#checks"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#contrast"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#compass"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#flag-2"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#flag-3"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#flag"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#forbid"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#help"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#info-circle"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#info"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#info-square"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#notification"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#question-mark"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#asterisk"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#cross"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#wifi-3"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#wifi-2"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#wifi-1"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#wifi"></use></svg>
		<svg class="icon"><use xlink:href="https://cdn.sayl.cloud/spices/icons/spices-icons.svg#wifi"></use></svg></div></template>